/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labIII;

import java.awt.EventQueue;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author johnny
 */
public class LoginFrame extends JFrame {

	/**
	 * Creates new form LoginFrame
	 */
	public LoginFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		// try {
		// for (UIManager.LookAndFeelInfo info : UIManager
		// .getInstalledLookAndFeels()) {
		// if ("Metal".equals(info.getName())) {
		// UIManager.setLookAndFeel(info.getClassName());
		// break;
		// }
		// }
		// } catch (ClassNotFoundException ex) {
		// java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
		// java.util.logging.Level.SEVERE, null, ex);
		// } catch (InstantiationException ex) {
		// java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
		// java.util.logging.Level.SEVERE, null, ex);
		// } catch (IllegalAccessException ex) {
		// java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
		// java.util.logging.Level.SEVERE, null, ex);
		// } catch (UnsupportedLookAndFeelException ex) {
		// java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
		// java.util.logging.Level.SEVERE, null, ex);
		// }
		GridBagConstraints gridBagConstraints;

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jTextFieldUsername = new JTextField();
		jTextFieldPassword = new JPasswordField();
		jButtonExit = new JButton();
		jButtonLogin = new JButton();
		jButtonRegistration = new JButton();

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(new GridBagLayout());

		jLabel1.setFont(jLabel1.getFont().deriveFont(
				jLabel1.getFont().getSize() + 5f));
		jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1.setText("Username:");
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.4;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jLabel1, gridBagConstraints);

		jLabel2.setFont(jLabel2.getFont().deriveFont(
				jLabel2.getFont().getSize() + 5f));
		jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel2.setText("Password:");
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.4;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jLabel2, gridBagConstraints);

		jTextFieldUsername.setFont(jTextFieldUsername.getFont().deriveFont(
				jTextFieldUsername.getFont().getSize() + 5f));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 100;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.6;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jTextFieldUsername, gridBagConstraints);

		jTextFieldPassword.setFont(jTextFieldPassword.getFont().deriveFont(
				jTextFieldPassword.getFont().getSize() + 5f));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 100;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.6;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jTextFieldPassword, gridBagConstraints);

		jButtonExit.setFont(jButtonExit.getFont().deriveFont(
				jButtonExit.getFont().getSize() + 5f));
		jButtonExit.setText("Exit");
		jButtonExit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButtonExitActionPerformed(evt);
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jButtonExit, gridBagConstraints);

		jButtonLogin.setFont(jButtonLogin.getFont().deriveFont(
				jButtonLogin.getFont().getSize() + 5f));
		jButtonLogin.setText("Login");
		jButtonLogin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButtonLoginActionPerformed(evt);
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jButtonLogin, gridBagConstraints);

		jButtonRegistration.setFont(jButtonRegistration.getFont().deriveFont(
				jButtonRegistration.getFont().getSize() + 5f));
		jButtonRegistration.setText("Registration");
		jButtonRegistration.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButtonRegistrationActionPerformed(evt);
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.3;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jButtonRegistration, gridBagConstraints);
		setTitle("Login");

		pack();
	}// </editor-fold>

	private void jButtonRegistrationActionPerformed(ActionEvent evt) {
		// TODO add your handling code here:
		RegistrationFrame r = new RegistrationFrame();
		r.setVisible(true);
	}

	private void jButtonLoginActionPerformed(ActionEvent evt) {
		// TODO add your handling code here:
		String username = jTextFieldUsername.getText();
		String password = jTextFieldPassword.getText();

		sql = "select *,count(*) as count from User where username = '"
				+ username + "' and password= '" + password + "';";// SQL语句
		System.out.println(sql);
		db1 = new DB(sql);// 创建DB对象
		try {
			ret = db1.pst.executeQuery();// 执行语句，得到结果集
			ret.next();
			System.out.println(ret.getInt("count"));
			if (ret.getInt(1) != 0) {
				ret.close();
				db1.close();// 关闭连接
				QueryJFrame q;
				q = new QueryJFrame("User");
				q.setVisible(true);
				q.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
				// this.dispose();
			} else {
				JOptionPane.showMessageDialog(this,
						"Wrong Password or Username.", "Login Fail",
						JOptionPane.ERROR_MESSAGE);
			}
		} catch (ClassNotFoundException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
	}

	private void jButtonExitActionPerformed(ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		LoginFrame l = new LoginFrame();
		l.setVisible(true);
	}

	// Variables declaration - do not modify
	private JButton jButtonExit;
	private JButton jButtonLogin;
	private JButton jButtonRegistration;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JPasswordField jTextFieldPassword;
	private JTextField jTextFieldUsername;
	private String sql = null;
	private DB db1 = null;
	private ResultSet ret = null;
	// End of variables declaration
}
