/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labIII;

import java.awt.EventQueue;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author johnny
 */
public class RegistrationFrame extends JFrame {

	/**
	 * Creates new form RegistrationFrame
	 */
	public RegistrationFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		GridBagConstraints gridBagConstraints;

		jLabel1 = new JLabel();
		jTextFieldUsername = new JTextField();
		jTextFieldPassword = new JTextField();
		jLabel2 = new JLabel();
		jButtonRegistration = new JButton();
		jButtonExit = new JButton();

		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(new GridBagLayout());

		jLabel1.setFont(jLabel1.getFont().deriveFont(
				jLabel1.getFont().getSize() + 5f));
		jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel1.setText("Username:");
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.4;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jLabel1, gridBagConstraints);

		jTextFieldUsername.setFont(jTextFieldUsername.getFont().deriveFont(
				jTextFieldUsername.getFont().getSize() + 5f));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 100;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.6;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jTextFieldUsername, gridBagConstraints);

		jTextFieldPassword.setFont(jTextFieldPassword.getFont().deriveFont(
				jTextFieldPassword.getFont().getSize() + 5f));
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.ipadx = 100;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.6;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jTextFieldPassword, gridBagConstraints);

		jLabel2.setFont(jLabel2.getFont().deriveFont(
				jLabel2.getFont().getSize() + 5f));
		jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
		jLabel2.setText("Password:");
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.4;
		gridBagConstraints.weighty = 0.4;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jLabel2, gridBagConstraints);

		jButtonRegistration.setFont(jButtonRegistration.getFont().deriveFont(
				jButtonRegistration.getFont().getSize() + 5f));
		jButtonRegistration.setText("Registration");
		jButtonRegistration.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButtonRegistrationActionPerformed(evt);
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jButtonRegistration, gridBagConstraints);

		jButtonExit.setFont(jButtonExit.getFont().deriveFont(
				jButtonExit.getFont().getSize() + 5f));
		jButtonExit.setText("Exit");
		jButtonExit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButtonExitActionPerformed(evt);
			}
		});
		gridBagConstraints = new GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = GridBagConstraints.BOTH;
		gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.weighty = 0.2;
		gridBagConstraints.insets = new Insets(10, 10, 10, 10);
		getContentPane().add(jButtonExit, gridBagConstraints);
		setTitle("Registration");
		pack();
	}// </editor-fold>

	private void jButtonRegistrationActionPerformed(ActionEvent evt) {
		// TODO add your handling code here:
		String username = jTextFieldUsername.getText();
		String password = jTextFieldPassword.getText();

		try {
			sql = "select *,count(*) as count from User where username = '"
					+ username + "';";// SQL语句
			System.out.println(sql);
			db1 = new DB(sql);// 创建DB对象
			ret=db1.pst.executeQuery();
			ret.next();
			if(ret.getInt("count")>0){
				System.out.println(ret.getInt("count"));
				JOptionPane.showMessageDialog(this,
						"Existing Username.", "Existing",
						JOptionPane.ERROR_MESSAGE);
			}else{
				sql="insert into User values('"+username+"','"+password+"');";
				System.out.println(sql);
				db1 = new DB(sql);// 创建DB对象
				if(!db1.pst.execute()){
					JOptionPane.showMessageDialog(this,
							"Registration Success.", "Success",
							JOptionPane.CLOSED_OPTION);
				}else{
					JOptionPane.showMessageDialog(this,
							"Registration Fail.", "Fail",
							JOptionPane.ERROR_MESSAGE);
					
				}
			}
		} catch (SQLException e) {
			// TODO 自动生成的 catch 块
			e.printStackTrace();
		}
	}

	private void jButtonExitActionPerformed(ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		RegistrationFrame r = new RegistrationFrame();
		r.setVisible(true);
	}

	// Variables declaration - do not modify
	private JButton jButtonExit;
	private JButton jButtonRegistration;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JTextField jTextFieldPassword;
	private JTextField jTextFieldUsername;
	private String sql = null;
	private DB db1 = null;
	private ResultSet ret = null;
	// End of variables declaration
}
